In [127]:
import numpy as np

## Операции над векторами

In [128]:
a = np.array([0, 1, 2, 3, 4])

In [129]:
b = np.array([5, 6, 7, 8, 9])

In [130]:
a.size

5

In [131]:
b.size

5

In [132]:
a.shape

(5,)

In [133]:
b.shape

(5,)

###  Сложение векторов

In [134]:
c = a + b

In [135]:
c

array([ 5,  7,  9, 11, 13])

In [138]:
x1 = [0, 1, 2, 3, 4]
x2 = [5, 6, 7, 8, 9]

In [139]:
x1 + x2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [141]:
c = np.add(a, b)
c

array([ 5,  7,  9, 11, 13])

### Вычитание векторов

In [143]:
a = np.array([5, 4, 8, 4, 3])
b = np.array([3, 5, 7, 1, 3])

In [144]:
d = a - b
d

array([ 2, -1,  1,  3,  0])

In [145]:
d = np.subtract(a, b)
d

array([ 2, -1,  1,  3,  0])

In [147]:
a.shape == b.shape

True

### Умножение вектора на скаляр

In [149]:
a = np.array([5, 4, 8, 4, 3])
a

array([5, 4, 8, 4, 3])

In [150]:
c = a * 2
c

array([10,  8, 16,  8,  6])

In [151]:
c = -10 * a
c

array([-50, -40, -80, -40, -30])

In [152]:
c = a * 0.5
c

array([2.5, 2. , 4. , 2. , 1.5])

In [154]:
2 * [1, 2, 3]

[1, 2, 3, 1, 2, 3]

In [155]:
a = np.array([5, 4, 8, 4, 3])
a

array([5, 4, 8, 4, 3])

In [156]:
a.dot(-10)

array([-50, -40, -80, -40, -30])

In [159]:
np.dot(a, -10)

array([-50, -40, -80, -40, -30])

In [161]:
np.multiply(-10, a)

array([-50, -40, -80, -40, -30])

### Скалярное произведение векторов

In [162]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [163]:
a.shape

(3,)

In [164]:
b.shape

(3,)

In [166]:
sp = a[0] * b[0] + a[1] * b[1] + a[2] * b[2]
sp

32

In [167]:
a @ b 

32

In [168]:
sp = np.dot(a, b)

## Операции с матрицами

In [170]:
A = np.array([[0, 1],
             [2, 3],
             [4, 5]])

In [172]:
B = np.array([[6, 7],
             [8, 9],
             [10, 11]])

In [173]:
A.shape

(3, 2)

In [174]:
B.shape

(3, 2)

### Сложение матриц

In [176]:
C = A + B
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [177]:
C = np.add(A, B)
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

### Вчитание матриц

In [178]:
A = np.array([[0, 1],
             [2, 3],
             [4, 5]])

In [179]:
B = np.array([[6, 7],
             [8, 9],
             [10, 11]])

In [180]:
D = A - B
D

array([[-6, -6],
       [-6, -6],
       [-6, -6]])

In [182]:
D = np.subtract(A, B)
D

array([[-6, -6],
       [-6, -6],
       [-6, -6]])

### Умножение матриц на скаляр

In [186]:
X = np.array([[1, 2], [3,4]])
X

array([[1, 2],
       [3, 4]])

In [187]:
Y = X * 3
Y

array([[ 3,  6],
       [ 9, 12]])

In [189]:
Y = np.dot(X, 2)
Y

array([[2, 4],
       [6, 8]])

### Умножение матриц

In [190]:
X1 = np.array([[1, 2],
              [3, 4], 
              [5, 6]])

In [191]:
X2 = np.array([[7, 8, 9, 10], 
              [11, 12, 13, 14]])

In [192]:
X1.shape[1] == X2.shape[0]

True

In [193]:
X1.shape, X2.shape

((3, 2), (2, 4))

In [197]:
Z = np.dot(X1, X2)
Z

array([[ 29,  32,  35,  38],
       [ 65,  72,  79,  86],
       [101, 112, 123, 134]])

In [195]:
Z.shape

(3, 4)

In [198]:
Z[0,0]

29

In [199]:
X1[0,0] * X2[0,0] + X1[0,1] * X2[1,0]

29

In [200]:
Z[0, 1]

32

In [202]:
X1[0, 0] * X2[0, 1] + X1[0, 1] * X2[1, 1]

32

### Модуль numpy.linalg возведение матрицы в квадрат

In [203]:
A = np.array([[0, 1, 2],
             [3, 4, 5],
             [6, 7, 8]])

In [204]:
A_square = np.dot(A, A)
A_square

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [205]:
A_square = np.linalg.matrix_power(A, 2)
A_square

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

### Создание единичной матрицы

Единичная матрица - квадратная мсатрица с единицами по главной диагонали и нулями в остальных ячейках

In [206]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Умножение матрицы на единичную матрицу

In [207]:
A = np.array([[1, 2],
             [3, 4],
             [5, 6]])

Случай 1

In [209]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [210]:
np.dot(A, I)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

Случай 2

In [211]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [212]:
np.dot(I, A)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

### Транспонирование матрицы

In [213]:
A = np.array([[1, 2],
             [3, 4],
             [5, 6]])

In [215]:
At = A.transpose()
At

array([[1, 3, 5],
       [2, 4, 6]])

In [217]:
At = A.T
At

array([[1, 3, 5],
       [2, 4, 6]])

Рассмотрим матрицы X и Y

In [218]:
X = np.array([[1, 2],
            [3, 4],
            [5, 6]])

In [219]:
Y = np.array([[0, 1],
             [2, 3],
             [4, 5],
             [6, 7]])

In [220]:
Yt = Y.T
Yt

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [221]:
np.dot(X, Yt)

array([[ 2,  8, 14, 20],
       [ 4, 18, 32, 46],
       [ 6, 28, 50, 72]])

### Вычисление определителя матрицы

In [225]:
A = np.array([[0,1, 2],
             [3,4, 5],
             [6,7, 8]])

In [226]:
np.linalg.det(A)

0.0

In [227]:
np.linalg.matrix_rank(A)

2

In [228]:
B = np.array([[7, 4, 5],
            [8, 3, 2],
             [6, 10, 12]])

In [230]:
np.linalg.det(B)

85.99999999999997

In [231]:
np.linalg.matrix_rank(B)

3

In [232]:
C = np.array([[1, 2],
             [3, 4],
             [5, 6]])

In [234]:
np.linalg.matrix_rank(C)

2

In [235]:
B = np.array([[7, 4, 5],
             [8, 3, 2],
             [6, 10, 12]])

In [236]:
B_inv = np.linalg.inv(B)
B_inv

array([[ 0.18604651,  0.02325581, -0.08139535],
       [-0.97674419,  0.62790698,  0.30232558],
       [ 0.72093023, -0.53488372, -0.12790698]])

In [237]:
B_inv2 = np.linalg.inv(B_inv)
B_inv2

array([[ 7.,  4.,  5.],
       [ 8.,  3.,  2.],
       [ 6., 10., 12.]])

### Автоматическое создание массивов

In [238]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [240]:
a = np.ones((5, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [242]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [243]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [244]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [245]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [246]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [247]:
np.arange(10, 0, -2)

array([10,  8,  6,  4,  2])

In [248]:
np.arange(1,10,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [251]:
np.linspace(0, 9.9, 100)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [252]:
np.logspace(0, 3, 4)

array([   1.,   10.,  100., 1000.])

In [253]:
np.logspace(0, 3, 5)

array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ,
       1000.        ])

In [254]:
np.random.sample()

0.6249423783641462

In [255]:
np.random.sample(3)

array([0.27417869, 0.67016556, 0.4213114 ])

In [256]:
np.random.sample((2, 3))

array([[0.72256214, 0.31573914, 0.17378732],
       [0.90200185, 0.1434395 , 0.47545547]])

In [257]:
np.random.sample((48, 64, 3))

array([[[0.98447234, 0.41827844, 0.07324504],
        [0.65804288, 0.34930032, 0.22454777],
        [0.30706199, 0.56704765, 0.66838165],
        ...,
        [0.40390517, 0.22351447, 0.39905298],
        [0.35904016, 0.41252933, 0.11503677],
        [0.50406838, 0.79527572, 0.86247355]],

       [[0.32758115, 0.73684582, 0.71839398],
        [0.49900739, 0.78541431, 0.7383164 ],
        [0.15404797, 0.78475004, 0.33980686],
        ...,
        [0.33833938, 0.59563646, 0.39273905],
        [0.16531677, 0.13925554, 0.29610923],
        [0.37761684, 0.09837342, 0.59726757]],

       [[0.4951529 , 0.14275435, 0.26743339],
        [0.2413713 , 0.55924261, 0.17620255],
        [0.69114003, 0.06128815, 0.49237022],
        ...,
        [0.01170875, 0.58677325, 0.7118943 ],
        [0.8973485 , 0.94623842, 0.68152825],
        [0.76938641, 0.89339762, 0.90390287]],

       ...,

       [[0.84177899, 0.04140842, 0.4485941 ],
        [0.32631907, 0.94707624, 0.12393447],
        [0.74246158, 0

Пример 1

In [258]:
np.random.randn(10)

array([-0.23438567,  0.58793787, -3.14660552,  0.14222853,  0.73295504,
       -2.56302884, -0.58721494, -0.50358768,  1.26994757,  1.56544886])

In [260]:
np.random.randn(3, 4)

array([[ 0.77735387,  0.07463134,  1.58303331, -0.22796446],
       [-1.13408328, -0.46946087, -0.78857641, -0.08875293],
       [-0.37205683,  1.25978131, -0.59355998, -0.0396079 ]])

In [261]:
np.random.randint(0, 10010)

8082

In [262]:
np.random.randint(0, 100, 10)

array([ 3, 86, 10, 55, 51, 44, 83, 92, 17, 30])

In [263]:
np.random.randint(0, 10, (3, 4))

array([[5, 9, 0, 1],
       [2, 9, 4, 1],
       [6, 2, 4, 1]])

In [264]:
np.random.choice([1, 2, 3, 4, 5])

4

In [265]:
np.random.choice([1, 2, 3, 4, 5], 3)

array([1, 4, 5])

In [266]:
np.random.seed(42)

In [267]:
np.random.choice([1, 2, 3, 4, 5], 3)

array([4, 5, 3])

In [268]:
np.random.choice([1, 2, 3, 4, 5], 3)

array([5, 5, 2])

In [269]:
np.random.seed(42)

In [270]:
np.random.choice([1, 2, 3, 4, 5], 3)

array([4, 5, 3])

### Изменение форимы массива

In [271]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [272]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [273]:
np.reshape(a, (3, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [274]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [275]:
a.resize(3, 4)

In [276]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [278]:
a = a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Соединение массивов

In [279]:
a = np.zeros((2, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [280]:
b = np.ones((2, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [282]:
v = np.vstack((a, b))
v

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [283]:
a.shape, b.shape, v.shape

((2, 3), (2, 3), (4, 3))

In [284]:
np.concatenate((a, b), axis = 0)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [285]:
h = np.hstack((a, b))
h

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [286]:
a.shape, b.shape, v.shape, h.shape

((2, 3), (2, 3), (4, 3), (2, 6))

In [288]:
np.concatenate((a, b), axis=1)

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [289]:
d = np.dstack((a, b))
d

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])

## Функции длдя работы с данными

### Выбор данных

In [291]:
a = np.random.randint(0, 20, 10)
a

array([ 5,  1,  0, 11, 11, 16,  9, 15, 14, 14])

In [292]:
a[a>10]

array([11, 11, 16, 15, 14, 14])

In [293]:
a[(a > 10) & (a % 2 == 0)]

array([16, 14, 14])

In [294]:
a[(a > 10) | (a % 3 == 0)]

array([ 0, 11, 11, 16,  9, 15, 14, 14])

In [295]:
a

array([ 5,  1,  0, 11, 11, 16,  9, 15, 14, 14])

In [298]:
np.where(a > 10)
# возвращает индексы

(array([3, 4, 5, 7, 8, 9]),)

In [300]:
a[np.where(a > 10)]

array([11, 11, 16, 15, 14, 14])

In [301]:
a = [1, 4, 7]
b = [9, 2, 5]

In [302]:
# Если в условии True, то берем элемент из массива a,
# если False - то из b
np.where([True, False, True], a, b)

array([1, 2, 7])

### Сортировка

In [303]:
a = np.array([[1, 3,9, 9],
             [5,0,1,5],
             [2,7,3,5]])

In [304]:
a[[0,2,1],:]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

In [305]:
a.argsort(axis=0)

array([[0, 1, 1, 1],
       [2, 0, 2, 2],
       [1, 2, 0, 0]])

In [324]:
a[:,0].argsort()

array([0, 2, 1])

In [325]:
a[a[:,0].argsort(), :]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

### Случайное переиешивание массивов

In [327]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [329]:
np.random.shuffle(a)

In [330]:
a

array([1, 8, 7, 5, 4, 9, 0, 3, 6, 2])

In [333]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [334]:
np.random.shuffle(a)
a

array([[ 9, 10, 11],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  1,  2]])

### Математические действия с массивами


In [335]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [336]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [337]:
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [338]:
np.sum(a)

21

In [339]:
a.sum(axis = 0)

array([5, 7, 9])

In [340]:
a.sum(axis=1)

array([ 6, 15])

In [341]:
10 + a

array([[11, 12, 13],
       [14, 15, 16]])

Поэлементное умножение (не матричное)

In [343]:
a = np.arange(12).reshape(3, -1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [345]:
b = np.arange(12, 24).reshape(-1, 4)
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [346]:
a * b

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

### Broadcasting (на примере сложения)

In [348]:
a = np.array([[2,5],
             [3,4],
             [6,1]])

In [351]:
b = np.array([1, 2])

In [352]:
a + b

array([[3, 7],
       [4, 6],
       [7, 3]])

In [354]:
c = np.array([[1],[2],[3]])

In [355]:
a + c

array([[3, 6],
       [5, 6],
       [9, 4]])

### Статистические функции

In [357]:
a = np.random.randint(0, 12, (3, 4))
a

array([[ 3,  8, 11,  1],
       [ 9,  8,  9,  4],
       [ 1,  3, 11, 11]])

In [358]:
a.min()

1

In [359]:
a.min(axis=0)

array([1, 3, 9, 1])

In [360]:
a.min(axis=1)

array([1, 4, 1])

In [361]:
a.max(axis=1)

array([11,  9, 11])

In [362]:
a.mean(axis=0) 
#среднее

array([ 4.33333333,  6.33333333, 10.33333333,  5.33333333])

In [363]:
a.std(axis=0)
#среднекватратическое отклонение

array([3.39934634, 2.3570226 , 0.94280904, 4.18993503])

### Запись и чтение массива из файла

In [364]:
np.save('a.npy', a)

In [365]:
b = np.load('a.npy')
b

array([[ 3,  8, 11,  1],
       [ 9,  8,  9,  4],
       [ 1,  3, 11, 11]])