In [1]:
import numpy as np

Задание 1

In [2]:
a = np.array([[1, 6],
             [2, 8],
             [3, 11],
             [3, 10],
             [1, 7]])

In [5]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

Задание 2

In [6]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3

In [11]:
a_centered_sp = np.array([a_centered[0,0] * a_centered[1,0] * a_centered[2,0] * a_centered[3,0] *a_centered[4,0],
                 a_centered[0,1] * a_centered[1,1] * a_centered[2,1] * a_centered[3,1] *a_centered[4,1]])
a_centered_sp/4

array([ 0.     , -1.39776])